# Include file which stores secrets for GitHub etc.
include ./secrets.conf

# Autorise use of flakes and nix-command
experimental-features = nix-command flakes
extra-trusted-users = lucasduport

# Remote builder for aarch64-linux
builders = ssh://remoteBuilder aarch64-linux
builders-use-substitutes = true

# Accelerate nix build
max-jobs = auto
cores = 0
build-cores = 0 
